### ISSUE TITLE
Not working...

### ISSUE THREAD

**Issue by andyhiles** [maximedegreve/TinyFaces-Sketch-Plugin#4]
Hi,

I'm having trouble getting this to work. 

I have installed the plugin but when I run it nothing happens. I don't get a pop up asking me which layer I would like to fill.

I'm using an artboard trying to fill an circle shape via the plugin. 

Am I doing it wrong?

Thanks

A

**Comment by maximedegreve** [comment]
Hi @andyhiles , what sketch version are you on?

**Comment by andyhiles** [comment]
Hi @maximedegreve I'm using the latest version (42)...
 
<img width="534" alt="screen shot 2017-02-09 at 9 10 12 am" src="https://cloud.githubusercontent.com/assets/16345804/22759707/8fb7ed4c-eea7-11e6-8c8e-e00b3905e9cf.png">

**Comment by maximedegreve** [comment]
@andyhiles okey dokey, that's weird. Can you make a video or show the exact steps? Also could you copy your console logs?

**Comment by andyhiles** [comment]
Yes no probs - Console screenshot attached 

<img width="695" alt="screen shot 2017-02-09 at 5 08 02 pm" src="https://cloud.githubusercontent.com/assets/16345804/22771378/7367f75c-eeea-11e6-93a9-a708be6e8da6.png">

**Comment by maximedegreve** [comment]
@andyhiles Hi Andy, Whoops! That was really helpful.

Get the latest version here: https://github.com/maximedegreve/TinyFaces-Sketch-Plugin/archive/master.zip

This should have the fix now :D  Let me know if that works.

**Comment by maximedegreve** [comment]
I'm closing this since the bug is fixed. If you run into any other issues. Let me know. 😄

**Comment by allisongrayce** [comment]
I'm getting the same error Andy described above, even with the latest version. I select the shapes I want to fill with images, go to plugins > tiny faces > fill with (either) and there is no prompt asking me what to fill with images.

**Comment by andyhiles** [comment]
Hi Guys, sorry for the delayed reply, I'm still getting the same issue too with the updated plugin. I will upload a console screenshot again
